### ISSUE TITLE
Application hosting section contains references to runme.io

### ISSUE THREAD

**Issue by BaileyJM02** [jexia/docs#61]
The [application hosting](https://docs.jexia.com/apphost) section still contains a large number of references to [runme.io](https://runme.io) which was discontinued last year, including but not limited to the `.runme/` directory and specification which can no longer be found, but still possibly used.

**Comment by reinos** [comment]
Hi @BaileyJM02! Good catch! Will discuss this internally and update the docs accordingly.

**Comment by veger** [comment]
I guess we just need to clean this up

**Comment by BaileyJM02** [comment]
Yeah, I didn't want to touch it though as it depends whether you want to continue to support the runme configuration or not. If yes, but not as runme, you could possibly move to `.jexia/config.yaml` and then create a new section for what values are supported within the specification etc.
